# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 058b1631d19a419679dcd9b6e899b73d15746c27a6063e1169a1a6ef6ade08acecff3594483c0d8df939d91efb72d339c8afc5747d862b6d9825786b8c5f7dad

test:
  secret_key_base: 4260e32be2d7e5bc635bbc43af1d34afe0194bc9938e91e58e075b495aadd8b2cf651569c56d584c4738fe59b21aa15190c3425f0a2833b8436577583bf145ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
